import type { Metadata } from "next";
import { notFound } from "next/navigation";
import {
  formatBlogDate,
  getAllBlogArticles,
  getAllBlogSlugs,
  getArticlesForCategory,
  getBlogArticleByAnySlug,
} from "@/content/blog";
import { BlogShell } from "@/components/blog/BlogShell";
import { BlogArticleContent } from "@/components/blog/BlogArticleContent";
import { brandName, ogImage, siteUrl } from "@/lib/seo";

type ArticlePageProps = {
  params: Promise<{ slug: string }>;
};

export function generateStaticParams() {
  // Include both Romanian and English slugs so /en/blog/[enSlug] is pre-built
  return getAllBlogSlugs().map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: ArticlePageProps): Promise<Metadata> {
  const { slug } = await params;
  const article = getBlogArticleByAnySlug(slug);

  if (!article) return {};

  const canonicalPath = `/blog/${article.slug}`;
  const hasEn = Boolean(article.en);

  return {
    title: article.title,
    description: article.summary,
    alternates: {
      canonical: canonicalPath,
      ...(hasEn
        ? {
            languages: {
              ro: `${siteUrl}${canonicalPath}`,
              en: `${siteUrl}/en${canonicalPath}`,
              "x-default": `${siteUrl}${canonicalPath}`,
            },
          }
        : {}),
    },
    openGraph: {
      type: "article",
      url: `${siteUrl}${canonicalPath}`,
      title: article.title,
      description: article.summary,
      // og:image is generated by opengraph-image.tsx (PNG, 1200×630)
      publishedTime: article.publishedAt,
      authors: [brandName],
      ...(hasEn ? { locale: "ro_RO", alternateLocale: ["en_US"] } : { locale: "ro_RO" }),
    },
    twitter: {
      card: "summary_large_image",
      title: article.title,
      description: article.summary,
    },
  };
}

export default async function BlogArticlePage({ params }: ArticlePageProps) {
  const { slug } = await params;
  // Accept both Romanian slugs and English slugs (e.g. after /en/ rewrite)
  const articleRo = getBlogArticleByAnySlug(slug);

  if (!articleRo) notFound();

  // Prepare English version if available (same article, translated fields merged)
  const articleEn = articleRo.en ? { ...articleRo, ...articleRo.en } : null;

  // Related articles in both languages (client will pick based on language)
  const relatedRo = getArticlesForCategory(articleRo.category.slug, "ro")
    .filter((item) => item.slug !== articleRo.slug)
    .slice(0, 2);
  const relatedEn = getArticlesForCategory(articleRo.category.slug, "en")
    .filter((item) => item.slug !== articleRo.slug)
    .slice(0, 2);

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: articleRo.title,
    description: articleRo.summary,
    datePublished: articleRo.publishedAt,
    dateModified: articleRo.publishedAt,
    inLanguage: articleRo.en ? ["ro-RO", "en"] : "ro-RO",
    author: { "@type": "Organization", name: brandName },
    publisher: {
      "@type": "Organization",
      name: brandName,
      logo: { "@type": "ImageObject", url: `${siteUrl}${ogImage}` },
    },
    articleSection: articleRo.category.title,
    url: `${siteUrl}/blog/${articleRo.slug}`,
    image: `${siteUrl}/blog/${articleRo.slug}/opengraph-image`,
    citation: articleRo.sources.map((source) => source.url),
    isAccessibleForFree: true,
    ...(articleRo.en
      ? {
          name: [
            { "@language": "ro", "@value": articleRo.title },
            { "@language": "en", "@value": articleRo.en.title },
          ],
        }
      : {}),
  };

  return (
    <BlogShell>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <BlogArticleContent
        articleRo={articleRo}
        articleEn={articleEn}
        relatedRo={relatedRo}
        relatedEn={relatedEn}
      />
    </BlogShell>
  );
}
